# Generated by Django 5.2.5 on 2025-08-26 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='fornecedora',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='Farmacia.fornecedora'),
            preserve_default=False,
        ),
    ]
