# Generated by Django 5.2.5 on 2025-08-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0002_fornecedora_medicamento_fornecedora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fornecedora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicamentos', to='Farmacia.fornecedora'),
        ),
    ]
