# Generated by Django 5.2.6 on 2025-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmacia', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
